export const REALESTATE_LIST_REQUEST = "REALESTATE_LIST_REQUEST"
export const REALESTATE_LIST_SUCCESS = "REALESTATE_LIST_SUCCESS"
export const REALESTATE_LIST_FAIL = "REALESTATE_LIST_FAIL"

export const REALESTATE_DETAILS_REQUEST = "REALESTATE_DETAILS_REQUEST"
export const REALESTATE_DETAILS_SUCCESS = "REALESTATE_DETAILS_SUCCESS"
export const REALESTATE_DETAILS_FAIL = "REALESTATE_DETAILS_FAIL"
